/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconFluentSelectAll24Regular: typeof import('~icons/fluent/select-all24-regular')['default']
    IconFluentShapeIntersect20Regular: typeof import('~icons/fluent/shape-intersect20-regular')['default']
    IconFluentShapeUnion20Regular: typeof import('~icons/fluent/shape-union20-regular')['default']
    IconFluentSquare20Regular: typeof import('~icons/fluent/square20-regular')['default']
    IconHeroiconsChevronUpDown20Solid: typeof import('~icons/heroicons/chevron-up-down20-solid')['default']
    IconPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IconPhArrowRight: typeof import('~icons/ph/arrow-right')['default']
    IconPhArrowSquareOut: typeof import('~icons/ph/arrow-square-out')['default']
    IconPhArrowUp: typeof import('~icons/ph/arrow-up')['default']
    IconPhCalendarBlank: typeof import('~icons/ph/calendar-blank')['default']
    IconPhCaretLeftBold: typeof import('~icons/ph/caret-left-bold')['default']
    IconPhCaretRightBold: typeof import('~icons/ph/caret-right-bold')['default']
    IconPhExport: typeof import('~icons/ph/export')['default']
    IconPhChartBarDuotone: typeof import('~icons/ph/chart-bar-duotone')['default']
    IconPhCheckBold: typeof import('~icons/ph/check-bold')['default']
    IconPhCheckCircle: typeof import('~icons/ph/check-circle')['default']
    IconPhChecks: typeof import('~icons/ph/checks')['default']
    IconPhInfo: typeof import('~icons/ph/info')['default']
    IconPhLightbulb: typeof import('~icons/ph/lightbulb')['default']
    IconPhLightning: typeof import('~icons/ph/lightning')['default']
    IconPhMagnifyingGlass: typeof import('~icons/ph/magnifying-glass')['default']
    IconPhNotePencilLight: typeof import('~icons/ph/note-pencil-light')['default']
    IconPhPlus: typeof import('~icons/ph/plus')['default']
    IconPhPlusBold: typeof import('~icons/ph/plus-bold')['default']
    IconPhPlusCircleBold: typeof import('~icons/ph/plus-circle-bold')['default']
    IconPhPlusSquareLight: typeof import('~icons/ph/plus-square-light')['default']
    IconPhSignOut: typeof import('~icons/ph/sign-out')['default']
    IconPhTrash: typeof import('~icons/ph/trash')['default']
    IconPhUserBold: typeof import('~icons/ph/user-bold')['default']
    IconPhWarning: typeof import('~icons/ph/warning')['default']
    IconPhX: typeof import('~icons/ph/x')['default']
    IconPhXCircle: typeof import('~icons/ph/x-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
